// Do not edit. This file is machine generated by the Resource DLL Wizard.

library FortranSnow;

{ITE} {LCID:00000419:00000419} {}
{ITE} {DFMFileType} {Main.dfm}
{ITE} {RCFileType} {FortranSnow_DRC.rc}

{$R 'Main.dfm' MainForm:TForm}
{$R 'FortranSnow_DRC.res' 'FortranSnow_DRC.rc'}

{$E RUS}

begin
end.